[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "any", "postgres"] }